### ISSUE TITLE
Code reorg

### ISSUE THREAD

**Issue by hairmare** [radiorabe/centos-rpm-fdk-aac-dabplus-odr#5]
See [here](https://groups.google.com/forum/#!topic/crc-mmbtools/SmnuWx_Ng-Y) and [here](https://groups.google.com/forum/#!topic/crc-mmbtools/-WtFnrDIxuU) for details.

**Comment by paraenggu** [comment]
Reflecting upstream project reorganisation with 8e804e39191da388a1e233766e53490126ad4e94 and the new repositories [centos-rpm-odr-audioenc](https://github.com/radiorabe/centos-rpm-odr-audioenc) & [centos-rpm-odr-padenc](https://github.com/radiorabe/centos-rpm-odr-padenc).
